Update readme.md
CamTosh/instagram-bot-dm pull request #36
Opened 2022-02-12 14:56 UTC by benjamrio

Grammar fixes

2022-02-12 16:13 UTC, dvershinin requested changes
Please don't introduces more grammmar problems 🤔

2022-03-13 20:53 UTC, CamTosh commented on readme.md
> +InstaDM createes a table `message` if it does not already exists.
```suggestion
InstaDM creates a table `message` if it does not already exists.
```

2022-03-13 20:53 UTC, CamTosh commented
@dvershinin can you resolve conflicts?

2022-03-13 21:39 UTC, dvershinin commented
I could, but "Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests". 

The changes to readme are so minor, I'd think just manually repeating them on master is easier than anything.

2023-04-08 21:50 UTC, closed without merging